### ISSUE TITLE
[Fatal Error] :7:252: The entity name must immediately follow the '&' in the entity reference.

### ISSUE THREAD

**Issue by ayunami2000** [kaklakariada/portmapper#110]
No ports show, yet it still forwards... This means I cannot delete forwardings either...
![image](https://user-images.githubusercontent.com/24785136/166857008-071c5cf7-ba90-48a6-96c2-36d2694c5ade.png)

```
DEBUG Getting port mapping 0...
DEBUG Got an exception with message 'The entity name must immediately follow the '&' in the entity reference.' for index 0, stop getting more mappings
TRACE Exception
org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1251)
	at org.bitlet.weupnp.GatewayDevice.simpleUPnPcommand(GatewayDevice.java:235)
	at org.bitlet.weupnp.GatewayDevice.getGenericPortMappingEntry(GatewayDevice.java:397)
	at org.chris.portmapper.router.weupnp.WeUPnPRouter.getPortMappings(WeUPnPRouter.java:127)
	at org.chris.portmapper.gui.PortMapperView.updatePortMappings(PortMapperView.java:329)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:440)
	at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:422)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
DEBUG Got null port mapping for index 0
```

**Comment by ayunami2000** [comment]
Oh also,
![image](https://user-images.githubusercontent.com/24785136/166857083-4b7cf6a0-adbd-4eeb-ab27-6d7e5caaea50.png)

**Comment by ayunami2000** [comment]
I may have used an "&" in the name...could that be it...?

**Comment by kaklakariada** [comment]
Yes, the & could be the problem, and that your router doesn't escape it properly. Please try to delete the mapping via the administration user interface of your router.

**Comment by kaklakariada** [comment]
Closing as stale.
