### ISSUE TITLE
java -jar portmapper problem

### ISSUE THREAD

**Issue by QNENet** [kaklakariada/portmapper#112]
What am I missing in trying to run portmapper as per the portmapper readme?

Ubuntu 22.04 
```
paulf@paulf-Modern-15-B5M:~$ java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+9)
OpenJDK 64-Bit Server VM (build 19.0.2+9, mixed mode, sharing)

```
```
paulf@paulf-Modern-15-B5M:~/QNE-DEV-4.3.6$ java -jar portmapper-2.2.2.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.chris.portmapper.PortMapperStarter.<clinit>(PortMapperStarter.java:26)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

```

**Comment by kaklakariada** [comment]
Hi @QNENet ,
I assume you are building Portmapper using Gradle? The build script generates two jar files in `build/libs/`: `portmapper-2.2.2.jar` and `portmapper-2.2.2-all.jar`. Only the last one (`-all.jar`)  contains all required libraries and can be executed with

```
java -jar build/libs/portmapper-2.2.2-all.jar
```

**Comment by QNENet** [comment]
I only used the jar available on maven and followed the readme in this repo. (portmapper-2.2.2.jar)
Perhaps there is a need for some explanation in the readme about the all version.
Thanks for this info.
