### ISSUE TITLE
Exception: Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by chris-scheurle** [kaklakariada/portmapper#3]
When I run
```
$ java -jar portmapper-2.0.0-alpha2.jar
```
I get
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/chris/portmapper/PortMapperStarter : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by chris-scheurle** [comment]
Oh, I forgot: running on `OS X 10.10.3` and
````
$ java -version
````
shows
````
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
````

**Comment by chris-scheurle** [comment]
Can't find a delete button anywhere ... the problem was, that termnal was using an outdated Java version.
````
/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java  -jar portmapper-2.0.0-alpha2.jar
````
does the trick.
