### ISSUE TITLE
portmapper crashes on launch

### ISSUE THREAD

**Issue by Lacedaemon** [kaklakariada/portmapper#30]
Tried the prebuilt binary, as well as compiling it manually on my machine.  What am I missing?

Here is the output from `java -jar portmapper-2.1.1.jar`:

    01:33:29.607 [AWT-EventQueue-0] WARN  o.jdesktop.application.LocalStorage - unspecified resource Application.vendorId using UnknownApplicationVendor
    01:33:29.609 [AWT-EventQueue-0] INFO  org.chris.portmapper.PortMapperApp - Using default configuration directory 'C:\Users\Nathan\AppData\Roaming\UnknownApplicationVendor\PortMapper'.
    01:33:29.610 [AWT-EventQueue-0] DEBUG org.chris.portmapper.PortMapperApp - Loading settings from file settings.xml
    01:33:29.625 [AWT-EventQueue-0] ERROR org.jdesktop.application.Application - Application class org.chris.portmapper.PortMapperApp failed to launch
    java.lang.ArrayIndexOutOfBoundsException: 0
            at java.beans.XMLDecoder.readObject(Unknown Source)
            at org.jdesktop.application.LocalStorage.load(LocalStorage.java:197)
            at org.chris.portmapper.PortMapperApp.loadSettings(PortMapperApp.java:159)
            at org.chris.portmapper.PortMapperApp.startup(PortMapperApp.java:78)
            at org.jdesktop.application.Application$1.run(Application.java:187)
            at java.awt.event.InvocationEvent.dispatch(Unknown Source)
            at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
            at java.awt.EventQueue.access$500(Unknown Source)
            at java.awt.EventQueue$3.run(Unknown Source)
            at java.awt.EventQueue$3.run(Unknown Source)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
            at java.awt.EventQueue.dispatchEvent(Unknown Source)
            at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
            at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
            at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
            at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
            at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
            at java.awt.EventDispatchThread.run(Unknown Source)
    Exception in thread "AWT-EventQueue-0" java.lang.Error: Application class org.chris.portmapper.PortMapperApp failed to launch
            at org.jdesktop.application.Application$1.run(Application.java:192)
            at java.awt.event.InvocationEvent.dispatch(Unknown Source)
            at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
            at java.awt.EventQueue.access$500(Unknown Source)
            at java.awt.EventQueue$3.run(Unknown Source)
            at java.awt.EventQueue$3.run(Unknown Source)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
            at java.awt.EventQueue.dispatchEvent(Unknown Source)
            at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
            at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
            at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
            at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
            at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
            at java.awt.EventDispatchThread.run(Unknown Source)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
            at java.beans.XMLDecoder.readObject(Unknown Source)
            at org.jdesktop.application.LocalStorage.load(LocalStorage.java:197)
            at org.chris.portmapper.PortMapperApp.loadSettings(PortMapperApp.java:159)
            at org.chris.portmapper.PortMapperApp.startup(PortMapperApp.java:78)
            at org.jdesktop.application.Application$1.run(Application.java:187)
            ... 14 more

**OS:**

    OS Name:                   Microsoft Windows 10 Home
    OS Version:                10.0.16299 N/A Build 16299

**Java Version:**

    java version "1.8.0_162"
    Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
    Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Thanks!

**Comment by kaklakariada** [comment]
Hi! Looks like there is an error reading the config files. As a workaround try deleting folder `C:\Users\Nathan\AppData\Roaming\UnknownApplicationVendor\PortMapper` after making a backup. You will need to enter the presets again.

I will investigate how to fix this.

**Comment by kaklakariada** [comment]
@Lacedaemon Thanks for reporting this! I fixed this in the master branch and will build a new release later.
