### ISSUE TITLE
"A JNI error has occured" when opening the jar

### ISSUE THREAD

**Issue by Oaklizard-2047** [kaklakariada/portmapper#60]
Everytime i try to open the jar, a dialog box would show up and said "A JNI error has occured, please check your installation".

**Comment by kaklakariada** [comment]
Usually this means your Java version is outdated. Please install Java 11 or later. If this does not help: run PortMapper from the command line using `java -jar portmapper.jar` and create a ticket containing the stack trace.

See https://github.com/kaklakariada/portmapper#portmapper-fails-to-start

**Comment by Bluelight82** [comment]
I have the same problem with updated Java! I only have 64-bit Java though.

**Comment by kaklakariada** [comment]
Please run PortMapper from the command line using `java -jar portmapper.jar` and post the error messages.

**Comment by Bluelight82** [comment]
I finally got around to extract the error message: 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/chris/portmapper/PortMapperStarter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by kaklakariada** [comment]
This error message means, that PortMapper is not compatible with the Java version installed on your machine. Please upgrade to Java 11. See https://github.com/kaklakariada/portmapper#install-java for details.

**Comment by kaklakariada** [comment]
I will close this. Please re-open if the issue still exists.

**Comment by Smankusors** [comment]
pardon me, but if some of us still wants to use Java 8 or Java 1.8... We can use PortMapper 2.1.1 or earlier versions, is that correct?

**Comment by kaklakariada** [comment]
Yes, you can use version 2.1.1 (https://github.com/kaklakariada/portmapper/releases/tag/v2.1.1) with Java 8.

**Comment by Smankusors** [comment]
> Yes, you can use version 2.1.1 (https://github.com/kaklakariada/portmapper/releases/tag/v2.1.1) with Java 8.

thanks for the confirmation. It's possible... to add this on the readme? Java 8 end of support is still long (year 2030) 💭

**Comment by kaklakariada** [comment]
Thanks for the hint, I added a [section about Java 1.8](https://github.com/kaklakariada/portmapper/blob/master/README.md#using-portmapper-with-java-18) to the readme.
