### ISSUE TITLE
Could not connect to router with CLing library

### ISSUE THREAD

**Issue by ItachiSan** [kaklakariada/portmapper#8]
As in title.
I expected it to work, but it does not. :/
The short log is this (INFO level):

```
[ency@antergos_E1-570G ~]$ java -jar Scrivania/portmapper-2.0.0-alpha2.jar 
15:21:38.527 [AWT-EventQueue-0] INFO  org.chris.portmapper.PortMapperApp - Using default configuration directory '/home/ency/.PortMapper'.
15:21:38.535 [AWT-EventQueue-0] DEBUG org.chris.portmapper.PortMapperApp - Loading settings from file settings.xml
15:21:38.548 [AWT-EventQueue-0] DEBUG org.chris.portmapper.PortMapperApp - Got settings [Settings: presets=[], useEntityEncoding=true, logLevel=INFO, routerFactoryClassName=org.chris.portmapper.router.sbbi.SBBIRouterFactory]
15:21:41.180 [pool-1-thread-1] INFO  org.chris.portmapper.PortMapperApp - Creating router factory for class org.chris.portmapper.router.sbbi.SBBIRouterFactory
15:21:41.184 [pool-1-thread-1] INFO  org.chris.portmapper.PortMapperApp - Searching for routers...
15:21:46.211 [pool-1-thread-1] INFO  org.chris.portmapper.PortMapperApp - Connected to router TL-WR841N
15:21:46.217 [pool-1-thread-1] INFO  o.c.p.router.sbbi.SBBIRouter - Got internal host name '192.168.0.1' for router.
15:21:46.309 [pool-1-thread-1] INFO  o.c.p.router.sbbi.SBBIRouter - Got external IP address 88.149.238.146 for router.
15:21:46.442 [pool-1-thread-1] INFO  o.c.p.r.s.SBBIPortMappingExtractor - Found 9 mappings, 0 mappings returned as null.
15:21:46.443 [pool-1-thread-1] INFO  o.c.portmapper.gui.PortMapperView - Found 9 mappings
15:21:54.695 [pool-1-thread-2] INFO  org.chris.portmapper.PortMapperApp - Creating router factory for class org.chris.portmapper.router.cling.ClingRouterFactory
15:21:54.699 [pool-1-thread-2] INFO  org.chris.portmapper.PortMapperApp - Searching for routers...
15:21:54.739 [pool-1-thread-2] INFO  org.fourthline.cling.UpnpServiceImpl - >>> Starting UPnP service...
15:21:54.740 [pool-1-thread-2] INFO  org.fourthline.cling.UpnpServiceImpl - Using configuration: org.fourthline.cling.DefaultUpnpServiceConfiguration
15:21:54.754 [pool-1-thread-2] INFO  o.fourthline.cling.transport.Router - Creating Router: org.fourthline.cling.transport.RouterImpl
15:21:54.759 [pool-1-thread-2] INFO  o.f.c.t.spi.MulticastReceiver - Creating wildcard socket (for receiving multicast datagrams) on port: 1900
15:21:54.761 [pool-1-thread-2] INFO  o.f.c.t.spi.MulticastReceiver - Joining multicast group: /239.255.255.250:1900 on network interface: wlp3s0
15:21:54.772 [pool-1-thread-2] INFO  o.f.cling.transport.spi.StreamServer - Created server (for receiving TCP streams) on: /192.168.0.110:58485
15:21:54.774 [pool-1-thread-2] INFO  o.f.cling.transport.spi.DatagramIO - Creating bound socket (for datagram input/output) on: /192.168.0.110
15:21:54.784 [pool-1-thread-2] INFO  org.fourthline.cling.UpnpServiceImpl - <<< UPnP service started successfully
15:21:55.354 [cling-13] WARN  o.f.c.p.RetrieveRemoteDescriptors - Received empty service descriptor:http://192.168.0.50:5000/ssdp/dummy.xml
15:21:55.356 [cling-13] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /ssdp/dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:73796E6F-6473-6D00-0000-0011323b7b60, Descriptor: http://192.168.0.50:5000/ssdp/desc-DSM-eth0.xml, Root: true
15:21:59.852 [AWT-EventQueue-0] WARN  o.c.portmapper.gui.PortMapperView - Could not connect to router: Did not find a router
org.chris.portmapper.router.RouterException: Did not find a router
    at org.chris.portmapper.PortMapperApp.connectRouter(PortMapperApp.java:207) ~[portmapper-2.0.0-alpha2.jar:na]
    at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:439) ~[portmapper-2.0.0-alpha2.jar:na]
    at org.chris.portmapper.gui.PortMapperView$ConnectTask.doInBackground(PortMapperView.java:427) ~[portmapper-2.0.0-alpha2.jar:na]
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295) ~[na:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
    at javax.swing.SwingWorker.run(SwingWorker.java:334) ~[na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]
15:21:59.855 [AWT-EventQueue-0] WARN  o.c.portmapper.gui.PortMapperView - Could not connect to router: Did not find a router
15:22:01.417 [cling-8] WARN  o.f.c.p.RetrieveRemoteDescriptors - Service descriptor retrieval failed: http://192.168.0.25:80/dummy.xml, 401 Unauthorized
15:22:01.417 [cling-8] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:upnp-BasicDevice-1_0-FCF528E50A9C, Descriptor: http://192.168.0.25:80/upnp/APDesc.xml, Root: true
15:22:31.452 [cling-3] WARN  o.f.c.p.RetrieveRemoteDescriptors - Service descriptor retrieval failed: http://192.168.0.25:80/dummy.xml, 401 Unauthorized
15:22:31.452 [cling-3] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:upnp-BasicDevice-1_0-FCF528E50A9C, Descriptor: http://192.168.0.25:80/upnp/APDesc.xml, Root: true
15:23:01.301 [cling-3] WARN  o.f.c.p.RetrieveRemoteDescriptors - Service descriptor retrieval failed: http://192.168.0.25:80/dummy.xml, 401 Unauthorized
15:23:01.302 [cling-3] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:upnp-BasicDevice-1_0-FCF528E50A9C, Descriptor: http://192.168.0.25:80/upnp/APDesc.xml, Root: true
15:23:31.473 [cling-3] WARN  o.f.c.p.RetrieveRemoteDescriptors - Service descriptor retrieval failed: http://192.168.0.25:80/dummy.xml, 401 Unauthorized
15:23:31.474 [cling-3] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:upnp-BasicDevice-1_0-FCF528E50A9C, Descriptor: http://192.168.0.25:80/upnp/APDesc.xml, Root: true
15:24:02.256 [cling-5] WARN  o.f.c.p.RetrieveRemoteDescriptors - Service descriptor retrieval failed: http://192.168.0.25:80/dummy.xml, 401 Unauthorized
15:24:02.257 [cling-5] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:upnp-BasicDevice-1_0-FCF528E50A9C, Descriptor: http://192.168.0.25:80/upnp/APDesc.xml, Root: true
15:24:32.509 [cling-12] WARN  o.f.c.p.RetrieveRemoteDescriptors - Service descriptor retrieval failed: http://192.168.0.25:80/dummy.xml, 401 Unauthorized
15:24:32.509 [cling-12] WARN  o.f.c.p.RetrieveRemoteDescriptors - Skipping invalid service '(RemoteService) Descriptor: /dummy.xml' of: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:upnp-BasicDevice-1_0-FCF528E50A9C, Descriptor: http://192.168.0.25:80/upnp/APDesc.xml, Root: true15:25:41.272 [AWT-EventQueue-0] WARN  org.chris.portmapper.PortMapperApp - Not connected to router. Can not disconnect.
15:25:41.274 [AWT-EventQueue-0] INFO  org.fourthline.cling.UpnpServiceImpl - >>> Shutting down UPnP service...
15:25:42.282 [AWT-EventQueue-0] INFO  org.fourthline.cling.UpnpServiceImpl - <<< UPnP service shutdown completed
```

While the ALL log is here:
http://paste.ubuntu.com/11820834/

**Comment by kaklakariada** [comment]
Hi ItachiSan,
I am sorry, but I can't help you there. PortMapper just uses some third party libraries. If none of the libraries works your router may be incompatible or UPnP is switched off.

**Comment by ItachiSan** [comment]
The old library works fine.
What I wanted to point out is that if this app looks for routers, it consider my Wifi repeater as a router.
